### ISSUE TITLE
Feature request: A way to get all models

### ISSUE THREAD

**Issue by qnkhuat** [camsaul/toucan2#143]
In some cases, we'd like to retrieve a list of all models easily.

We currently achieve this with the toucan1 compatibility by `(descendants :toucan1/model)`.

An example use case from Metabase: https://github.com/metabase/metabase/blob/220ad8f13bb56e53ee5c57a6bf2386276e1e1218/enterprise/backend/src/metabase_enterprise/serialization/v2/seed_entity_ids.clj#L37

**Comment by camsaul** [comment]
Unlike in Toucan 1, models don't need to be registered with Toucan 2 in any way. They're just plain keywords, and you're not required to implement any methods for them unless you want to. So there's no way for Toucan 2 to know which keywords you're using as models. 

I'd highly recommend having all your models derive from some base keyword so you can call `descendants` on it, but that is not a requirement.
