### ISSUE TITLE
Why are we creating new maps when calling `instance` with a map?

### ISSUE THREAD

**Issue by camsaul** [camsaul/toucan2#164]
Seems pointless and wasteful, unless it's a transient map of some sort.

https://github.com/camsaul/toucan2/blob/e8ac3422a979406f0441ee0b52a6383aefd455fc/src/toucan2/instance.clj#L270-L272

**Comment by crisptrutski** [comment]
We know that `m` is not a transient, as we've called `(some-fn map? nil?)` above and `(map? (transient {}))` returns false. I suspect that this copying is to protect from the map being an instance corresponding to another map, due to the previous case being commented out.
